ADD: migrate-action in Makefile

diff --git a/PRACTICE/Makefile b/PRACTICE/Makefile
--- a/PRACTICE/Makefile
+++ b/PRACTICE/Makefile
@@ -3,14 +3,16 @@ export
 
 COMPOSE := docker-compose
 
+MIGRATE_DATABASE_URL := postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@go-practice-postgres:5432/$(POSTGRES_DB)?sslmode=disable
+
 env-up:
-	$(COMPOSE) up -d go-practice-postgres
+	@$(COMPOSE) up -d go-practice-postgres
 
 env-stop:
-	$(COMPOSE) stop go-practice-postgres
+	@$(COMPOSE) stop go-practice-postgres
 
 env-down:
-	$(COMPOSE) down
+	@$(COMPOSE) down
 
 env-cleanup:
 	@read -p "Clear all volume environment files? [y/N]: " ans; \
@@ -21,10 +23,10 @@ env-cleanup:
 	fi
 
 env-logs:
-	$(COMPOSE) logs -f go-practice-postgres
+	@$(COMPOSE) logs -f go-practice-postgres
 
 env-ps:
-	$(COMPOSE) ps -a
+	@$(COMPOSE) ps -a
 
 migrate-create:
 	@if [ -z "$(name)" ]; then \
@@ -33,3 +35,19 @@ migrate-create:
 	fi
 	$(COMPOSE) run --rm go-practice-migrate \
 		create -ext sql -dir . -seq $(name)
+
+migrate-up:
+	@make migrate-action action=up
+
+migrate-down:
+	@make migrate-action action=down
+
+migrate-action:
+	@if [ -z "$(action)" ]; then \
+		echo "A required parameter 'action' is missing. Usage: make migrate-action action=up"; \
+		exit 1; \
+	fi
+	$(COMPOSE) run --rm go-practice-migrate \
+		-path . \
+		-database "$(MIGRATE_DATABASE_URL)" \
+		"${action}"
